version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_api
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./secure_storage:/app/secure_storage
      - ./backend:/app # Mount backend code for live changes

  celery-worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app # Mount backend code for celery worker

  flower-server:
    build:
      context: .
      dockerfile: backend/fl_server/Dockerfile
    container_name: flower_server
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app # Mount entire project root to /app
    command: python /app/backend/fl_server/server.py # Adjust command to reflect new path

  fl-node:
    build:
      context: ./fl-node
      dockerfile: Dockerfile
    container_name: fl_node_client
    depends_on:
      - flower-server
    volumes:
      - ./fl-node:/app # Mount fl-node code
      - ./fl-node/data:/app/data # Mount data for the client
    command: python -m client # This should match the CMD in fl-node/Dockerfile

volumes:
  postgres_data: